<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\Nikolas\GitHubRepos\FE-Buddy-DEV\FeBuddy\FEBuddyLibrary\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\Nikolas\GitHubRepos\FE-Buddy-DEV\FeBuddy\FEBuddyLibrary\.editorconfig" />
  </ItemGroup>

</Project>
