<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\background.jpg" />
    <None Remove="Images\FEB_EARTH_SS2_BW.jpg" />
    <None Remove="Images\FE_BUDDY_icon.ico" />
    <None Remove="Images\logo.PNG" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Model\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome.Sharp" Version="6.2.1" />
    <PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\background.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\FEB_EARTH_SS2_BW.jpg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\FE_BUDDY_icon.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\logo.PNG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
