<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net6.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Model\" />
    <Folder Include="View\Controls\" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Github-Repos\FE-Buddy-DEV\FeBuddy\WPF\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\Github-Repos\FE-Buddy-DEV\FeBuddy\WPF\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FEBuddyLibrary\FEBuddyLibrary.csproj" />
  </ItemGroup>

</Project>
